#!/bin/bash

source ./gcl_bin/gcl_check.sh
source ./gcl_bin/set_on_gcl.sh

take_repo()
{
    while [[ -z $repo ]] || [[  $repo != "github" &&  $repo != "blih" ]]; do
        read -p 'Selectionne un répertoire Git [github/blih] ? ' repo
        if [ -z $repo ]; then
            echo -e "\nVeuillez entrer un Répertoire\n"
        elif [ $repo = "github" ]; then
            lin='git clone git@github.com:'
        elif [ $repo = "blih" ]; then
            lin='git clone git@git.epitech.eu:/'
        else
            echo -e "\nVeuillez entrer un Répertoire Valide\n"
        fi
    done
}

github_checker()
{
    if [[ $repo = "github" ]]; then
        cu='https://github.com/'$user'?tab=repositories'
        hr='<a href="/'$user'/'
        echo $cu
        echo $hr
        curl $cu > url
        cat url | grep "$hr" > project 
        rm -rf url
        
        while read -r rp; do
            tr -d $hr -d " "
        done < project
    fi
}

take_user()
{
    read -p 'Entre le nom du propriétaire : ' user
    while [ -z $user ]; do
        echo -e '\nVeuillez entrer un nom\n'
        read -p 'Entre le nom du propriétaire : ' user
    done
    new_main_user
    if [ $? -eq 0 ]; then
        new_reccurent_user
    fi
}

take_project()
{
    read -p 'Entre le nom du projet : ' project
    if [ -z $project ]; then
        echo 'Veuillez entrer un nom de projet'
        exit
    fi
}

check_files
want_reset $1
use_main_user $1
take_repo
take_user
github_checker
take_project

$lin$user'/'$project 
